dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
networks:
  default: 'ganache-kellspell'
  rinkeby:
    eth_usd_price_feed: '0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False  
  development:
    verify: False
  ganache-kellspell: 
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}